#!/bin/bash

#SBATCH --partition=compute
#SBATCH --job-name=metagenome
#SBATCH --mail-type=ALL
#SBATCH --mail-user=katelane@mit.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=180G
#SBATCH --time=48:00:00
#SBATCH --output=metagenome%j.log
#export OMP_NUM_THREADS=36

#Run the setup.sh script first

#Note - This script can be broken into parts in order to run on cluster if jobs must be shorter than 48hrs.

##Create conda environment
conda env create -f LANE_metagenome.yml


##Activate conda environment:
conda activate metagenome

#Define rootdir on your computing environment, this is the directory if you type `pwd` inside the directory from cloning this repo. For example, on the Poseidon HPC:
rootdir=/vortexfs1/omics/env-bio/collaboration/jahala/


##Download Data
cd ${rootdir}/data/raw_data/
for i in `cat  access_list_mg.txt`
do
fasterq-dump --split-3 --verbose -O metagenome/ $i
done
#access list is present in /tools/ directory, and in /data/raw_data/ directory. Accession list is also here: SRR10411456


##Trim Reads
cd ${rootdir}/data/raw_data/metagenome

for i in `cat ../access_list_mg.txt`
do
trimmomatic PE -threads 36 ${i}_1.fastq  ${i}_2.fastq ${i}_1.trimmed.fastq.gz ${i}_1un.trimmed.fastq.gz ${i}_2.trimmed.fastq.gz ${i}_2un.trimmed.fastq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:40:15 MINLEN:75
done
#un is unpaired output, TruSeq3-PE.fa is present in the raw_data/metagenome/ directory and in the the /tools/ directory for reference

##Filter and Remove Diatom Reads
bowtie2 -x bt2/diatom.fa -1 /vortexfs1/omics/env-bio/collaboration/jahala/data/raw_data/metagenome/sra/SRR10411456_1.trimmed.fastq.gz -2 /vortexfs1/omics/env-bio/collaboration/jahala/data/raw_data/metagenome/sra/SRR10411456_2.trimmed.fastq.gz --un-conc bowtie_metagenome_host_removed
(jahala_clean_metagenome) [katherine.lane@poseidon-l2 sra]$ mv bowtie_metagenome_host_removed.2 bowtie_metagenome_host_removed.2.fq
(jahala_clean_metagenome) [katherine.lane@poseidon-l2 sra]$ mv bowtie_metagenome_host_removed.1 bowtie_metagenome_host_removed.1.fq

##Determine Taxonomic Composition of Metagenome
Kaiju
 wget https://kaiju.binf.ku.dk/database/kaiju_db_refseq_2021-02-26.tgz

##Assembly
megahit
megahit -t 36 -o megahit_assembly2 -1 bowtie_metagenome_host_removed.1.fq -2 bowtie_metagenome_host_removed.2.fq

##Calculate Coverage
#map reads to assembly
dir=/vortexfs1/omics/env-bio/collaboration/jahala/data/raw_data/metagenome/sra
bwa index ${dir}/megahit_assembly2/final.contigs.fa
bwa mem -t 48 ${dir}/megahit_assembly2/final.contigs.fa ${dir}/bowtie_metagenome_host_removed.1.fq ${dir}/bowtie_metagenome_host_removed.2.fq > aln-pe.sam
samtools sort -@48 aln-pe.sam -o aln-pe.sorted.bam


##Bin Genomes
metabat2
jgi_summarize_bam_contig_depths --outputDepth depth.txt aln-pe.sorted.bam
metabat2 -i final.contigs.fa -a depth.txt -o bins_dir/bin

##Assess Genomes
#to reduce redundancy in conda environments, use the checkm install in the MAGS environment
conda deactivate
conda activate MAGS

cd ${rootdir}/d]
checkm lineage_wf --pplacer_threads 1 --tab_table -t 16 -x fna ${rootdir}/data/raw_data/MAGS/ ${rootdir}/data/raw_data/MAGS/checkm_results
tail -9 checkm*.log | head -7 > checkm_stats.tsv


