#!/bin/bash

#SBATCH --partition=compute
#SBATCH --job-name=MAGS
#SBATCH --mail-type=ALL
#SBATCH --mail-user=[YOUR_EMAIL]
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=180G
#SBATCH --time=3:00:00
#SBATCH --output=MAGS_%j.log
#export OMP_NUM_THREADS=36

#Run the setup.sh script first

##Create conda environment
conda env create -f LANE_MAGS.yml


##Activate conda environment:
conda activate MAGS


##CHECKM for stats on MAGS
cd output/MAGS/checkm/
checkm lineage_wf --pplacer_threads 1 --tab_table -t 16 -x fna output/MAGS/checkm output/MAGS/checkm/checkm_results
tail -8 checkm*.log | head -6 > checkm_stats_NCBI.tsv #create stats table


